### ISSUE TITLE
Add issues templates

### ISSUE THREAD

**Issue by thibautjombart** [epiverse-trace/linelist#26] opened 2022-05-09 13:57 UTC
Add templates for:

- [ ] questions
- [ ] other things

**Comment by Bisaloo** [comment] 2022-08-31 10:53
It sounds like we should have generic templates applied to all repos (unless overridden in the case of more specific needs).

**Comment by Bisaloo** [comment] 2022-10-11 09:09
Duplicate of https://github.com/epiverse-trace/.github/issues/1.

**Closed by Bisaloo** 2022-10-11 09:09 UTC
Labels: enhancement
